characterName = ("Character: Lukas de Jong")
specialAbility = ("Special Move: Uses ten meters of LED strips to temporarily disable movement")
mania = ("Mania: 571")
power = ("Power: over 9000")
speed = ("Speed: Fast")

print(characterName)
print(specialAbility)
print(mania)
print(power)
print(speed)
